language: objective-c
osx_image: xcode7.3
env:
  - TOOLCHAINS=swift
before_install:
  - TOOLCHAIN_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a
  - curl -O https://swift.org/builds/development/xcode/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-osx.pkg
  - sudo installer -pkg ${TOOLCHAIN_VERSION}-osx.pkg -target /
script:
  - swift build
  - swift test
